spring:
  profiles: eureka2
  application:
    name: eurekaCenter

server:
  port: 9002

eureka:
  instance:
    hostname: slf.eureka.center2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://slf.eureka.center1:9001/eureka/,http://slf.eureka.center2:9002/eureka/,http://slf.eureka.center3:9003/eureka/